/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_final;

import javax.swing.JOptionPane;
import static proyecto_final.Ventana_Registro.nombre;

/**
 *
 * @author Usuario
 */
public class jVentanaAdivina extends javax.swing.JFrame {

    int intentos = 0;
    int aleatorio = 0;
    public jVentanaAdivina() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        txtsalida.append("Empieza el juego, ingresa un numero del 1 al 100\n");
        aleatorio = (int) (Math.random()*100);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtsalida = new javax.swing.JTextArea();
        btnreiniciar = new javax.swing.JButton();
        btnjugar = new javax.swing.JButton();
        txtnumero = new javax.swing.JTextField();
        btnsalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuCuenta = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtsalida.setColumns(20);
        txtsalida.setRows(5);
        jScrollPane1.setViewportView(txtsalida);

        btnreiniciar.setText("Reiniciar juego");
        btnreiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreiniciarActionPerformed(evt);
            }
        });

        btnjugar.setText("Jugar");
        btnjugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjugarActionPerformed(evt);
            }
        });

        txtnumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fondo_1.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/genio.png"))); // NOI18N

        menuInicio.setBackground(new java.awt.Color(102, 0, 255));
        menuInicio.setForeground(new java.awt.Color(102, 0, 255));
        menuInicio.setText("Inicio");
        menuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInicioActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Pagina de inicio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuInicio.add(jMenuItem1);

        jMenuItem2.setText("Pagina principal");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuInicio.add(jMenuItem2);

        jMenuBar1.add(menuInicio);

        menuCuenta.setText("Mi cuenta");

        jMenuItem3.setText("Mis datos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuCuenta.add(jMenuItem3);

        jMenuItem4.setText("Cerrar sesion");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuCuenta.add(jMenuItem4);

        jMenuBar1.add(menuCuenta);

        jMenu3.setText("Juegos");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Tragamonedas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Adivina el número");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("El gato y el ratón");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Piedra, papel o tijera");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btnjugar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(btnreiniciar))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(btnsalir))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnjugar))
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnreiniciar))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(btnsalir))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnjugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjugarActionPerformed
        try{  
            int numero = Integer.parseInt(txtnumero.getText());
            if (numero == aleatorio){
              txtsalida.append("Felicitaciones");
              txtsalida.append(", el numero es: "+aleatorio+"\n");
              txtsalida.append("Acertaste en: "+intentos+" intentos" );
              btnjugar.setEnabled(false);
              btnreiniciar.setEnabled(true);
            }
            else if(numero < aleatorio)
                txtsalida.append(numero+" es bajo\n");
            else 
                txtsalida.append(numero+" es alto\n");
            txtnumero.setText("");
            txtnumero.requestFocus();
            intentos++;
        }catch(NumberFormatException ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnjugarActionPerformed

    private void btnreiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreiniciarActionPerformed
        btnjugar.setEnabled(true);
        btnreiniciar.setEnabled(false);
        intentos = 0;
        aleatorio = (int)(Math.random()*100);
        txtsalida.setText("");
        txtnumero.requestFocus();
        txtsalida.append("Empieza el juego, ingresa un numero del 1 al 100\n");
    }//GEN-LAST:event_btnreiniciarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        String nombre1 = "";
        nombre1 = Ventana_Registro.nombre;
        if (nombre1 == null) {
            Ventana_Principal f1 = new Ventana_Principal();
            f1.setVisible(true);
          this.setVisible(false);
        } else {
            Ventana_Principal f1 = new Ventana_Principal();
            f1.jLabel2.setVisible(false);
          f1.jLabel3.setVisible(false);
          f1.jLabel4.setVisible(false);
          f1.jLabel5.setVisible(false);
          f1.jLabel6.setVisible(false);
          f1.entradaCorreo.setVisible(false);
          f1.entradaContraseña.setVisible(false);
          f1.jSeparator1.setVisible(false);
          f1.jButton1.setVisible(false);
          f1.jButton2.setVisible(false);
          f1.jPanel2.setVisible(false);
          f1.jLabel7.setVisible(true);
          f1.jLabel8.setVisible(true);
          f1.jLabel8.setText(Ventana_Registro.nombre);
          f1.setVisible(true);
          this.setVisible(false);
        }
    }//GEN-LAST:event_btnsalirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String nombre = "";
        nombre = Ventana_Registro.nombre;
        if (nombre != null) {
            int aux= JOptionPane.showConfirmDialog(null, "Si vuelve a la pagina inicial se cerrara su sesion"
                +"\n¿Estas seguro de salir de la pagina principal?");
            if (aux==JOptionPane.YES_OPTION) {
                Ventana_Inicio f1 = new Ventana_Inicio();
                f1.setVisible(true);
                Ventana_Registro.nombre = null;
                Ventana_Registro.apellido = null;
                Ventana_Registro.contraseña = null;
                Ventana_Registro.correo = null;
                Ventana_Registro.nacimiento = null;
                Ventana_Registro.sexo = null;
                this.setVisible(false);
            }  else if(aux==JOptionPane.NO_OPTION){
            }
        } else {
            Ventana_Inicio f1 = new Ventana_Inicio();
            f1.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        String nombre1 = "";
        nombre1 = Ventana_Registro.nombre;
        if (nombre1 == null) {
            Ventana_Principal f1 = new Ventana_Principal();
            f1.setVisible(true);
            this.setVisible(false);
        } else {
            Ventana_Principal f1 = new Ventana_Principal();
            f1.jLabel2.setVisible(false);
          f1.jLabel3.setVisible(false);
          f1.jLabel4.setVisible(false);
          f1.jLabel5.setVisible(false);
          f1.jLabel6.setVisible(false);
          f1.entradaCorreo.setVisible(false);
          f1.entradaContraseña.setVisible(false);
          f1.jSeparator1.setVisible(false);
          f1.jButton1.setVisible(false);
          f1.jButton2.setVisible(false);
          f1.jPanel2.setVisible(false);
          f1.jLabel7.setVisible(true);
          f1.jLabel8.setVisible(true);
          f1.jLabel8.setText(Ventana_Registro.nombre);
          f1.setVisible(true);
          this.setVisible(false);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuInicioActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Ventana_Cuenta f1 = new Ventana_Cuenta();
        f1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        String nombre = "";
        nombre = Ventana_Registro.nombre;
        if (nombre != null) {
            int aux= JOptionPane.showConfirmDialog(null, "¿Estas seguro de cerrar tu sesión?");
            if (aux==JOptionPane.YES_OPTION) {
                Ventana_Principal f2 = new Ventana_Principal();
                Ventana_Registro.nombre = null;
                Ventana_Registro.apellido = null;
                Ventana_Registro.contraseña = null;
                Ventana_Registro.correo = null;
                Ventana_Registro.nacimiento = null;
                Ventana_Registro.sexo = null;
                this.setVisible(false);
            }  else if(aux==JOptionPane.NO_OPTION){
            }
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jVentanaTragamonedas f1 = new jVentanaTragamonedas();
        f1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        JOptionPane.showMessageDialog(null, "El juego del gato y el raton es de: "
            +"\n         2 JUGADORES");
        jVentanaGato f1 = new jVentanaGato();
        f1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Ventana_Piedra f1 = new Ventana_Piedra();
        f1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
 
    }//GEN-LAST:event_jMenu3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jVentanaAdivina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jVentanaAdivina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jVentanaAdivina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jVentanaAdivina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jVentanaAdivina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnjugar;
    private javax.swing.JButton btnreiniciar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuCuenta;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextArea txtsalida;
    // End of variables declaration//GEN-END:variables
}
