/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_final;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edgarpablo
 */
public class Ventana_Cuenta extends javax.swing.JFrame {
    String nombre = "", apellido,correo, nacimiento, sexo;
    DefaultTableModel mod;
    String datos[][]={};
    String titulo[]={"NOMBRE","APELLIDO", "CORREO O NÚMERO", "FECHA DE NACIMIENTO", "SEXO"};    
    
    public Ventana_Cuenta() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        mod = new DefaultTableModel(datos, titulo);
        
        nombre = Ventana_Registro.nombre;
        apellido = Ventana_Registro.apellido;
        correo = Ventana_Registro.correo;
        nacimiento = Ventana_Registro.nacimiento;
        sexo = Ventana_Registro.sexo;
        String datos[]={nombre, apellido,correo, nacimiento, sexo};
        jTableDatos.setModel(mod);
        DefaultTableModel mod = (DefaultTableModel) jTableDatos.getModel();
        mod.addRow(datos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDatos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuCuenta = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableDatos.setForeground(new java.awt.Color(102, 0, 255));
        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NOMBRE", "APELLIDO", "CORREO", "NACIMIENTO", "SEXO"
            }
        ));
        jTableDatos.setSelectionBackground(new java.awt.Color(102, 0, 255));
        jScrollPane1.setViewportView(jTableDatos);
        if (jTableDatos.getColumnModel().getColumnCount() > 0) {
            jTableDatos.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTableDatos.getColumnModel().getColumn(0).setHeaderValue("NOMBRE");
            jTableDatos.getColumnModel().getColumn(1).setPreferredWidth(40);
            jTableDatos.getColumnModel().getColumn(1).setHeaderValue("APELLIDO");
            jTableDatos.getColumnModel().getColumn(2).setPreferredWidth(60);
            jTableDatos.getColumnModel().getColumn(2).setHeaderValue("CORREO");
            jTableDatos.getColumnModel().getColumn(3).setPreferredWidth(60);
            jTableDatos.getColumnModel().getColumn(3).setHeaderValue("NACIMIENTO");
            jTableDatos.getColumnModel().getColumn(4).setPreferredWidth(30);
            jTableDatos.getColumnModel().getColumn(4).setHeaderValue("SEXO");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 680, 110));

        jLabel8.setFont(new java.awt.Font("Apple Braille", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 255));
        jLabel8.setText("JUGADOR 1");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Avatar (1).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 100, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 90, 30));

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 350));

        menuInicio.setText("Inicio");

        jMenuItem1.setText("Pagina de inicio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuInicio.add(jMenuItem1);

        jMenuItem2.setText("Pagina principal");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuInicio.add(jMenuItem2);

        jMenuBar1.add(menuInicio);

        menuCuenta.setText("Mi cuenta");

        jMenuItem3.setText("Mis datos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuCuenta.add(jMenuItem3);

        jMenuItem4.setText("Cerrar sesión");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuCuenta.add(jMenuItem4);

        jMenuBar1.add(menuCuenta);

        jMenu3.setText("Juegos");

        jMenuItem5.setText("Tragamonedas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Adivina el número");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("El gato y el ratón");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Piedra, papel o tijera");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String nombre = "";
        nombre = Ventana_Registro.nombre;
        if (nombre != null) {
            int aux= JOptionPane.showConfirmDialog(null, "Si vuelve a la pagina inicial se cerrara su sesion"
                    +"\n¿Estas seguro de salir de la pagina principal?");
            if (aux==JOptionPane.YES_OPTION) {
            Ventana_Inicio f1 = new Ventana_Inicio();
            f1.setVisible(true);
            Ventana_Registro.nombre = null;
            Ventana_Registro.apellido = null;
            Ventana_Registro.contraseña = null;
            Ventana_Registro.correo = null;
            Ventana_Registro.nacimiento = null;
            Ventana_Registro.sexo = null;
            this.setVisible(false);
        }  else if(aux==JOptionPane.NO_OPTION){
        }
        } else {
            Ventana_Inicio f1 = new Ventana_Inicio();
            f1.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       
        if (nombre == "") {
            Ventana_Principal f1 = new Ventana_Principal();
            f1.setVisible(true);
          this.setVisible(false);
        } else {
            Ventana_Principal f1 = new Ventana_Principal();
            f1.jLabel2.setVisible(false);
          f1.jLabel3.setVisible(false);
          f1.jLabel4.setVisible(false);
          f1.jLabel5.setVisible(false);
          f1.jLabel6.setVisible(false);
          f1.entradaCorreo.setVisible(false);
          f1.entradaContraseña.setVisible(false);
          f1.jSeparator1.setVisible(false);
          f1.jButton1.setVisible(false);
          f1.jButton2.setVisible(false);
          f1.jPanel2.setVisible(false);
          f1.jLabel7.setVisible(true);
          f1.jLabel8.setVisible(true);
          f1.jLabel8.setText(Ventana_Registro.nombre);
          f1.setVisible(true);
          this.setVisible(false);
        }
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        String nombre = "";
        nombre = Ventana_Registro.nombre;
        if (nombre != null) {
            int aux= JOptionPane.showConfirmDialog(null, "¿Estas seguro de cerrar tu sesión?");
            if (aux==JOptionPane.YES_OPTION) {
            Ventana_Principal f2 = new Ventana_Principal();
            Ventana_Registro.nombre = null;
            Ventana_Registro.apellido = null;
            Ventana_Registro.contraseña = null;
            Ventana_Registro.correo = null;
            Ventana_Registro.nacimiento = null;
            Ventana_Registro.sexo = null;
            this.setVisible(false);
        }  else if(aux==JOptionPane.NO_OPTION){
        }
        }
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jVentanaTragamonedas f1 = new jVentanaTragamonedas();
        f1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Ventana_Piedra f1 = new Ventana_Piedra();
        f1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        JOptionPane.showMessageDialog(null, "El juego del gato y el raton es de: "
                                           +"\n         2 JUGADORES");
        jVentanaGato f1 = new jVentanaGato();
        f1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        jVentanaAdivina f1 = new jVentanaAdivina();
        f1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        String nombre1 = "";
        nombre1 = Ventana_Registro.nombre;
        if (nombre1 == null) {
            Ventana_Principal f1 = new Ventana_Principal();
            f1.setVisible(true);
            this.setVisible(false);
        } else {
            Ventana_Principal f1 = new Ventana_Principal();
            f1.jLabel2.setVisible(false);
            f1.jLabel3.setVisible(false);
            f1.jLabel4.setVisible(false);
            f1.jLabel5.setVisible(false);
            f1.jLabel6.setVisible(false);
            f1.entradaCorreo.setVisible(false);
            f1.entradaContraseña.setVisible(false);
            f1.jSeparator1.setVisible(false);
            f1.jButton1.setVisible(false);
            f1.jButton2.setVisible(false);
            f1.jPanel2.setVisible(false);
            f1.jLabel7.setVisible(true);
            f1.jLabel8.setVisible(true);
            f1.jLabel8.setText(Ventana_Registro.nombre);
            f1.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDatos;
    private javax.swing.JMenu menuCuenta;
    private javax.swing.JMenu menuInicio;
    // End of variables declaration//GEN-END:variables
}
